# background            #fdf6e3
# foreground            #52676f
# cursor                #52676f
# selection_background  #e9e2cb
# selection_foreground  #262626
# color0 #e4e4e4
# color8 #ffffd7
# color1 #d70000
# color9 #d75f00
# color2 #5f8700
# color10 #585858
# color3 #af8700
# color11 #626262
# color4 #0087ff
# color12 #808080
# color5 #af005f
# color13 #5f5faf
# color6 #00afaf
# color14 #8a8a8a
# color7 #262626
# color15 #1c1c1c

# active_tab_foreground #262626
# active_tab_background #e4e4e4
# inactive_tab_foreground #262626
# inactive_tab_background #ffffd7

# active_border_color #d75f00

background            #fdf6e3
foreground            #657b83

cursor                #657b83
cursor_text_color     #fdf6e3

selection_background  #dfdac7
selection_foreground  #657b83

# Black and bright black
# Dark theme
# color0 #eee8d5
# color8 #fdf6e3

# light theme
color0 #073642
color8 #002b36

# Red and bright red
color1 #dc322f
color9 #cb4b16

# Green and bright green
color2 #859900
color10 #586e75

# Yellow and bright yellow
color3 #b58900
color11 #657b83

# Blue and bright blue
color4 #268bd2
color12 #839496

# Magenta and bright magenta
color5 #d33682
color13 #6c71c4

# Cyan and bright cyan
color6 #2aa198
color14 #93a1a1

# White and bright white
# Dark theme
# color7 #073642
# color15 #002b36

# Light theme
color7 #eee8d5
color15 #fdf6e3

active_tab_foreground #073642
active_tab_background #beb9aa
inactive_tab_foreground #073642
inactive_tab_background #e3ddcc

active_border_color #cb4b16
