#!/usr/bin/bash
set -o pipefail

source /usr/local/share/bwrap_share/strict_rules

ro_bind_path+=(
    "/etc/highlight"
    "$HOME/.config/lf"
    "$1"
)

bind_path+=(
    "$HOME/.cache/lf_thumbnails"
)

source /usr/local/share/bwrap_share/generate_args

res="$(
    bwrap \
        --unshare-user \
        --unshare-ipc \
        --unshare-pid \
        --unshare-net \
        --unshare-uts \
        --unshare-cgroup \
        \
        --disable-userns \
        --hostname my-pc \
        --proc /proc \
        --cap-drop ALL \
        --new-session \
        --die-with-parent \
        --seccomp 9 \
        \
        --dev /dev \
        "${dev_bind[@]}" \
        "${tmpfs[@]}" \
        "${ro_bind[@]}" \
        "${bind[@]}" \
        "${hide[@]}" \
        "${unhide_ro[@]}" \
        "${unhide[@]}" \
        "${symbolic_link[@]}" \
        "${remount_ro[@]}" \
        bash "$HOME"/.config/lf/lf_kitty_preview "$@" \
        9</usr/local/share/seccomp-filter/default_seccomp_filter.bpf
)"

error_code="$?"

if [ -n "${_NVIM_+1}" ] || [ "$error_code" -eq 1 ]; then
    printf "%s" "$res"

elif [ "$error_code" -eq 2 ]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}" "$res" </dev/null >/dev/tty

fi

exit 1
