hl.on("hyprland.start", function()
    -- Do not start waybar as systemd unit. hyprlshutdown will not work properly.
    -- All others, try to start as systemd service to enable auto restart.
    hl.exec_cmd("waybar")
    hl.exec_cmd("systemctl --user start app-blueman@autostart.service")
    hl.exec_cmd("systemctl --user start app-firewall\\\\x2dapplet@autostart.service")
    hl.exec_cmd("systemctl --user start app-nm\\\\x2dapplet@autostart.service")
    hl.exec_cmd("systemctl --user start app-org.fcitx.Fcitx5@autostart.service")
    hl.exec_cmd("systemctl --user start idle_service.service")
    hl.exec_cmd("systemctl --user start keepassxc.service")
    hl.exec_cmd("systemctl --user start low-battery-notification.service")
    hl.exec_cmd("systemctl --user start polkit-agent.service")
    hl.exec_cmd("systemctl --user start swaybg.service")
    hl.exec_cmd("systemctl --user start swayosd.service")
    hl.exec_cmd("systemctl --user start udiskie.service")
end)
