----- Auto start treesitter -----
vim.api.nvim_create_autocmd("FileType", {
    pattern = "*",
    callback = function(args)
        local ok = pcall(vim.treesitter.start)
        if ok then
            vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"
        end
    end,
})

return {
    {
        "romus204/tree-sitter-manager.nvim",
        event = "VeryLazy",
        opts = {
            ensure_installed = {
                "asm",
                "awk",
                "bash",
                "bibtex",
                "c",
                "c_sharp",
                "cairo",
                "cmake",
                "comment",
                "corn",
                "cpp",
                "css",
                "csv",
                "cuda",
                "diff",
                "doxygen",
                "fsharp",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "go",
                "gpg",
                "haskell",
                "haskell_persistent",
                "hjson",
                "html",
                "html_tags",
                "htmldjango",
                "http",
                "hurl",
                "hyprlang",
                "ini",
                "java",
                "javadoc",
                "javascript",
                "jq",
                "jsdoc",
                "json",
                "json5",
                "julia",
                "kconfig",
                "kitty",
                "latex",
                "llvm",
                "lua",
                "luadoc",
                "markdown",
                "markdown_inline",
                "matlab",
                "mermaid",
                "meson",
                "nginx",
                "ninja",
                "objdump",
                "ocaml",
                "ocaml_interface",
                "ocamllex",
                "passwd",
                "perl",
                "php",
                "php_only",
                "phpdoc",
                "powershell",
                "printf",
                "python",
                "r",
                "regex",
                "requirements",
                "rust",
                "sql",
                "ssh_config",
                "strace",
                "superhtml",
                "sway",
                "swift",
                "todotxt",
                "toml",
                "tsv",
                "typescript",
                "typst",
                "udev",
                "vhdl",
                "vim",
                "vimdoc",
                "vue",
                "xml",
                "yaml",
                "zig",
                "ziggy",
                "ziggy_schema",
                "zsh"
            },
        }
    },
}
