#!/usr/bin/bash
set -e

[ ! -d "$XDG_RUNTIME_DIR/lf_progress" ] && exit 0

readarray -td '' selected < <(
     fd --type x --glob -- "*.sh" "$XDG_RUNTIME_DIR/lf_progress" |
          fzf -i --multi --exact --reverse --prompt="Kill operation:" --delimiter / \
               --with-nth -1 --preview "less {}" --print0
)

for f in "${selected[@]}"; do
     pkill -15 -f "^(/usr/bin|/bin|)bash $f" >/dev/null 2>&1 || true
     rm "$f"
done
