#!/usr/bin/bash
set -e

fd --unrestricted --exact-depth 1 --type file --type symlink \
    ".*" "$HOME/.config/hypr/fzf_menu/snippets" |
    sort |
    fzf --print0 -i --no-multi --exact --delimiter / --with-nth -1 --preview 'cat {}' \
        --prompt="Copy snippet: " --info=default --layout=reverse --tiebreak=index |
    xargs -0 --no-run-if-empty -I{} bash -c 'setsid wl-copy < "{}" >/dev/null 2>&1 &'
