#!/bin/bash

bak_path="$HOME/Sync/Bak"
if ! mountpoint -q -- "$bak_path"; then
    echo "Bak not mounted"
    read -n 1 -s -r -p "Press any key to continue"
    exit 0
fi

# fusermount -u "$bak_path"
umount "$bak_path"

exit_code="$?"
if [ "$exit_code" -eq 0 ]; then
    rmdir --ignore-fail-on-non-empty "$bak_path"
    echo "Unmounted bak"
fi

read -n 1 -s -r -p "Press any key to continue"
