#!/usr/bin/bash
set -e

readarray -td '' arr < <(
    udiskie-info --all --output "{mount_path}" |
        grep -v "^$" |
        fzf --multi --exact --reverse --prompt="Eject USB:" --delimiter / --with-nth -1 --print0
)

for usb_path in "${arr[@]}"; do
    if mount | grep "type fuse.gocryptfs" | grep -q "$usb_path"; then
        notify-send "'$usb_path' is mounted using gocryptfs."
        continue
    fi
    setsid udiskie-umount --detach "$usb_path" >/dev/null 2>&1 &
done

sleep 0.1
