#!/usr/bin/bash
set -e

[ ! -d "$XDG_RUNTIME_DIR/lf_progress" ] && exit 0

cat <<\EOF >"$XDG_RUNTIME_DIR/check_file_operation.sh"
#!/bin/bash
set -e
echo "File operations in progress:"
while read -r f; do
    filename="$(basename -- "$f")"
    action="${filename%%_*}"
    dest="$(head -n2 "$f" | tail -n1 | sed -E "s:^##\s*::")"
    [ -z "$dest" ] && dest="Unknown"

    echo "${filename}: ${dest}"
    filename="${filename//./_}"

    if tmux list-sessions 2>/dev/null | rg -q -F "$filename"; then
        if [[ "$action" =~ (trash|rm|zip|7z|clamscan|extract|tar) ]]; then
            line="$(tmux capture-pane -peC -t "$filename":0 | grep -v -e '^$' | tail -n1)"
            echo "$line"

        else
            echo "$(tmux capture-pane -peC -t "$filename":0 | grep -v -e '^$' | tail -n1 | awk '{print $1, $2, $3, $4}')"

        fi
    fi
    echo
done < <(fd  --type x --glob -- "*.sh" "$XDG_RUNTIME_DIR/lf_progress")
progress

EOF
chmod 700 "$XDG_RUNTIME_DIR/check_file_operation.sh"

if [ "$(hyprctl dispatch 'hl.dsp.focus({window = \"class:file_operation_progress\"})')" != "ok" ]; then
    setsid kitty --class file_operation_progress -- watch -n 1 --no-title \
        bash "$XDG_RUNTIME_DIR/check_file_operation.sh" >/dev/null 2>&1 </dev/null &
fi

sleep 0.1
